# Generated by Django 4.2.6 on 2026-03-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='diamonds/')),
                ('carat', models.FloatField()),
                ('color', models.CharField(max_length=10)),
                ('clarity', models.CharField(max_length=20)),
                ('cut', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('certification', models.CharField(max_length=20)),
            ],
        ),
    ]
