# Generated by Django 4.2.6 on 2026-03-08 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamond',
            name='certification',
        ),
        migrations.AddField(
            model_name='diamond',
            name='auction_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
