# Generated by Django 4.2.6 on 2026-03-08 15:43

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_diamond_certification_diamond_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond',
            name='auction_end',
            field=models.DateTimeField(default=auction.models.Diamond.auction_default),
        ),
    ]
