# Generated by Django 4.2.6 on 2026-03-08 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0004_alter_diamond_auction_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField(blank=True, null=True)),
                ('total_bids', models.IntegerField(default=0)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('was_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Auction History',
                'verbose_name_plural': 'Auction Histories',
                'ordering': ['-ended_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount', 'created_at'], 'verbose_name': 'Bid', 'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterModelOptions(
            name='diamond',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Diamond', 'verbose_name_plural': 'Diamonds'},
        ),
        migrations.AddField(
            model_name='diamond',
            name='auction_status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('winner_declared', 'Winner Declared'), ('payment_pending', 'Payment Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', help_text='Current status of the auction', max_length=20),
        ),
        migrations.AddField(
            model_name='diamond',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Payment deadline for winner', null=True),
        ),
        migrations.AddField(
            model_name='diamond',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this diamond was last updated'),
        ),
        migrations.AddField(
            model_name='diamond',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='User who won this auction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diamond',
            name='winner_declared_at',
            field=models.DateTimeField(blank=True, help_text='When winner was declared', null=True),
        ),
        migrations.AddField(
            model_name='diamond',
            name='winning_bid',
            field=models.ForeignKey(blank=True, help_text='The winning bid for this auction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_auctions', to='auction.bid'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['diamond', '-amount'], name='auction_bid_diamond_04c886_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['user'], name='auction_bid_user_id_8b57ff_idx'),
        ),
        migrations.AddIndex(
            model_name='diamond',
            index=models.Index(fields=['auction_status', 'auction_end'], name='auction_dia_auction_9ffb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='diamond',
            index=models.Index(fields=['winner'], name='auction_dia_winner__7eebbd_idx'),
        ),
        migrations.AddIndex(
            model_name='diamond',
            index=models.Index(fields=['auction_end'], name='auction_dia_auction_c1ed63_idx'),
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='diamond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.diamond'),
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
