# Generated by Django 4.2.6 on 2026-04-16 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0005_auctionhistory_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('created', 'Payment Created'), ('pending', 'Payment Pending'), ('captured', 'Payment Captured'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diamond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.diamond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['razorpay_order_id'], name='auction_pay_razorpa_67135e_idx'), models.Index(fields=['user', 'status'], name='auction_pay_user_id_983602_idx'), models.Index(fields=['diamond'], name='auction_pay_diamond_a4d2cd_idx')],
            },
        ),
    ]
